sudo: false
language: node_js
node_js:
  - "4"
  - "6"
  - "8"
  - "9"
after_success:
  - nyc report --reporter=text-lcov | coveralls
matrix:
  fast_finish: true
notifications:
  irc:
    channels:
      - "irc.freenode.org#unshift"
    on_success: change
    on_failure: change
